kind: pipeline
name: default

steps:
- name: verify & build
  image: node
  environment:
    SUPABASE_URL:
      from_secret: NEXT_PUBLIC_SUPABASE_URL
    SUPABASE_ANON_KEY:
      from_secret: NEXT_PUBLIC_SUPABASE_ANON_KEY
  commands:
    - echo "NEXT_PUBLIC_SUPABASE_URL=$${SUPABASE_URL}\nNEXT_PUBLIC_SUPABASE_ANON_KEY=$${SUPABASE_ANON_KEY}" > .env.local
    - npm install
    - npm run build
  when:
    branch:
      exclude:
        - main


- name: build docker image
  image: plugins/docker
  enviroment: 
    SUPABASE_URL:
      from_secret: NEXT_PUBLIC_SUPABASE_URL   
    SUPABASE_ANON_KEY:
      from_secret: NEXT_PUBLIC_SUPABASE_ANON_KEY 
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_token
    build_args_from_env:
      - SUPABASE_URL
      - SUPABASE_ANON_KEY 
    dockerfile: ./Dockerfile
    repo: xanya/week6
    tags:
      - ${DRONE_COMMIT:0:7}